permissions:
    backends:
        file:
            file: permissions.yml
    backend: file
    createUserRecords: false
    allowOps: false
    debug: false
    user-add-groups-last: false
    basedir: plugins/PermissionsEx
    informplayers:
        changes: false
multiserver:
    use-netevents: true
updater: true
alwaysUpdate: false